permalink: pretty
markdown: kramdown

title: Single Sign On List
author: Brian Epstein
description:
    List of Service Providers (SP) that support Single Sign On (SSO)
    with Identity Providers (IdP) that your organization supports.
url: https://supportsso.org
repo: https://github.com/theias/supportsso
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - vendor
    - websites_schema.yml
